---
  - hosts: local
    sudo: yes
    vars:
        activator_version: 1.2.10
    tasks:
        - name: ensure java is at the latest version
          apt: pkg=openjdk-7-jdk state=latest
        - name: ensure unzip is at the latest version
          apt: pkg=unzip state=latest
        - name: ensure vim is the latest version
          apt: pkg=vim state=latest
        - name: ensure git is the latest version
          apt: pkg=git state=latest
        - name: create play group
          group: name=play state=present
        - name: create play user
          user: name=play group=play groups="sudo" state=present
        - name: create /home/play/code dir
          file: dest=/home/play/Code mode=755 owner=play group=play state=directory
        - name: create /opt/activator dir
          file: dest=/opt/activator mode=755 owner=play group=play state=directory
        - name: get Activator
          get_url: url="http://downloads.typesafe.com/typesafe-activator/1.2.10/typesafe-activator-1.2.10.zip" dest=/tmp/activator-1.2.10.zip
        - name: unzip acivator
          unarchive: src=/tmp/activator-1.2.10.zip dest=/tmp/
        - name: move activator to opt
          local_action: synchronize src=/tmp/activator-1.2.10/ dest=/opt/activator/ recursive=yes delete=yes
        - name: give play user permissions for opt/activator
          file: path=/opt/activator/ state=directory recurse=true mode=755
        - name: export path variable
          raw: "echo 'export PATH=$PATH:/opt/activator' >> /home/play/.bashrc"
        - name: export java options variable
          raw: "echo 'export _JAVA_OPTIONS=\"-Duser.home=/home/play/Code\"' >> /home/play/.bashrc "

